stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - ${data.raw_path}
    outs:
      - ${data.processed_path}
    params:
      - data.raw_path
      - data.processed_path

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - ${data.processed_path}
    outs:
      - ${data.model_path}
    params:
      - data.processed_path
      - data.model_path
